#开发环境
server:
  port: 8800
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  messages:
    basename: i18n/messages
  thymeleaf:
    cache: false
  redis:
    host: #你的redis服务器地址
    port: #redis端口号
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数


#    lettuce:
#        pool:
#          max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#          max-idle: 10 # 连接池中的最大空闲连接
#          min-idle: 5 # 连接池中的最小空闲连接
#          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

logging:
  level:
    root: info
    com.sjy: debug
  file:
    name: log/blog/dev.log